int test() {
    int a = 1;
    int b = 2;

    print(a + b);
}

int test2(int a, bool b) {
    print(a);
    print(b);
}

int testret() {
    return 1000;
}

void old() {
    int a = input();
    test2(1 + 1 + testret(), false);
    test();

    int c = 1;
    int b = input();

    print(5 + (1 > 2) - 1);
}

void main() {
    int a = input();
    int b = input();

    if(a > b) {
        print(a);
    }

    if(b >= a) {
        print(b);
    }

    a = input();

    while(a < 10) {
        print(a);
        a = input();
    }
}